### PR TITLE
PropertyGrid methods for filling in values at application startup

### PR DESCRIPTION
**Pull request by JamesBremner**
See issue #7

### CODE REVIEW

**Comment by JamesBremner** [comment]
That should have been:

_Find property in grid from category name and property label_

This allows me to pre-populate the property values from a database on startup

```
        std::vector< std::string >& res =
            pinmed::Config::db::Query( "SELECT indata1_port FROM pelexmixer_network;");

        pg.find("InData1","Port").value( res[0] );
```

**Comment by JamesBremner** [comment]
These additions allow me to populate the property grid from a database on startup like this:

```
        std::vector< std::string >& res =
            pinmed::Config::db::Query( "SELECT * FROM pelexmixer_network;");

        pg.find("InData1","Port")=res[0];
        pg.find("Pelex","Sample Freq")=res[9];

        res = pinmed::Config::db::Query( "SELECT * FROM pelex_input;");

        pg.find("Pelex Port 1","Port")= res[3];
        pg.find("Pelex Port 1","IP or Log")= res[2];
        pg.find("Pelex Port 2","Port")= res[6];
        pg.find("Pelex Port 2","IP or Log")= res[5];

       ... and so on for over 100 properties
```

**Comment by JamesBremner** [comment]
Commit https://github.com/besh81/nana-extra/pull/8/commits/e02f916156ca7787725405440e2a6c6b0cce6a87 is for issue #10

**Comment by besh81** [comment]
Thanks for your PR!
You made a great work and add a lot of improvements.
I'm going to add a flag where to specify the behavior on focus lost: update or reload the old one.

**Pull request merged**
